### ISSUE TITLE
Tradução capítulo de decoradores

### ISSUE THREAD

**Issue by leportella** [joanasouza/intermediatePython#1]

**Comment by leportella** [comment]
Devemos traduzir as funções? Eu pensei em traduzir as strings dos prints mas não as funções em sim.

Por ex, ficaria assim:

```
def SomeFunction():
    print("Essa função faz isso")
```

**Comment by joanasouza** [comment]
@leportella Podemos deixar as funções em inglês, seguindo o padrão do livro original.
